### ISSUE TITLE
Some useful links for the vRLI Community Page

### ISSUE THREAD

**Issue by vmspot** [bethsouza/LogInsight#1]
Hey Elizabeth! Thanks so much for starting another awesome community page! Here are some useful links to get this page going. Feel free to add them at your discretion. Matt

What's new in vRealize Log Insight 8.1 https://blogs.vmware.com/management/2020/04/whats-new-in-vrealize-log-insight-8-1.html

Announcing vRealize Log Insight 8.1 https://blogs.vmware.com/management/2020/03/announcing-vrealize-log-insight-8-1.html

vRealize Log Insight Product Page https://www.vmware.com/products/vrealize-log-insight.html

vRealize Log Insight Documentation https://docs.vmware.com/en/vRealize-Log-Insight/index.html

vRealize Log Insight Sizing Calculator https://kb.vmware.com/s/article/60355

vRealize Log Insight Community Content Pack Exchange https://www.vmware.com/go/log-insight-content-exchange

Forwarding Kubernetes Logs to vRealize Log Insight via Fluentd - Nico Guerrera https://blogs.vmware.com/management/2019/04/forwarding-kubernetes-logs-to-vrealize-log-insight-via-fluentd.html

Forwarding vRealize Log Insight events to a SIEM solution - Yogita Patil https://blogs.vmware.com/management/2020/01/forwarding-vrealize-log-insight-events-to-a-siem-solution.html

vRealize Log Insight Index Partitions and Variable Retention Deep Dive - Matt Bradford https://blogs.vmware.com/management/2020/05/vrealize-log-insight-index-partitions-and-variable-retention-deep-dive.html

vRealize Log Insight Agent Multi-Destination Support - Yogita Patil https://blogs.vmware.com/management/2017/06/vrealize-log-insight-agent-multi-destination-support.html

Steve Flanders Blog https://sflanders.net/tag/log-insight/

vRealize Log Insight Agent Install and Configuration - Matt Bradford https://youtu.be/LMDcXCWBa1o

How to Troubleshoot with vRealize Log Insight - Nico Guerrera https://youtu.be/93ErLFg_8sY

Create an alert in vRLI for missing vSAN 7 File Shares - Kim Bottu https://vmusketeers.com/2020/04/07/create-an-alert-for-missing-vsan-7-file-shares-in-vrli/

VMware vRealize Log Insight content pack for Cisco ASA - Mischa Buijs https://be-virtual.net/vmware-vrealize-log-insight-content-pack-for-cisco-asa/

Twitter:
Julie Roman @__vRO
Yogita Patil @nitinyogi6
Nico Guerrera @nicomgu

**Comment by bethsouza** [comment]
Hi Matt, thanks so much for your help!
